---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.11

jobs:
  test:
    executor: golang

    working_directory: /go/src/github.com/flant/multiwerf
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build_release:
    executor: golang

    working_directory: /go/src/github.com/flant/multiwerf
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: ./go-release-build.sh $CIRCLE_SHA1


  build_release_on_tag:
    executor: golang

    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: ./publish.sh release-github --tag $CIRCLE_TAG

workflows:
  version: 2
  multiwerf:
    jobs:
    - test:
        filters:  # required since `build_release_on_tag` has tag filters AND requires `test`
          tags:
            only: /.*/
          branches:
            only: /.*/
    - build_release:
        requires:
        - test
        filters:
          branches:
            only: master
    - build_release_on_tag:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}([-+].+|[^-.]*)$/
          branches:
            ignore: /.*/

